# Generated by Django 6.0 on 2025-12-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('idTag', models.TextField(primary_key=True, serialize=False)),
                ('tagValue', models.TextField(verbose_name='Valor de la etiqueta')),
            ],
            options={
                'ordering': ('tagValue',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('idUsuario',),
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('pictureUrl', models.URLField(verbose_name='URL de la imagen')),
                ('etiquetas', models.ManyToManyField(related_name='artistas_etiquetados', to='main.etiqueta')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoEscucha', models.IntegerField(verbose_name='Tiempo de escucha')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'ordering': ('idUsuario', '-tiempoEscucha'),
            },
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(verbose_name='Día')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anyo', models.IntegerField(verbose_name='Año')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('idTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etiqueta')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'ordering': ('idUsuario', 'idArtista'),
            },
        ),
    ]
