# Generated by Django 6.0 on 2025-12-15 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('generos', models.CharField(max_length=500, verbose_name='Géneros')),
                ('formato_emision', models.CharField(max_length=50, verbose_name='Formato de emisión')),
                ('num_episodios', models.IntegerField(default=0, verbose_name='Número de episodios')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='Id Usuario')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
            options={
                'ordering': ('id_usuario', 'anime'),
            },
        ),
    ]
