# Generated by Django 5.2.6 on 2025-12-15 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeID', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Título')),
                ('generos', models.TextField(verbose_name='Géneros')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('episodios', models.IntegerField(verbose_name='Número de episodios')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField(verbose_name='Id Usuario')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
            options={
                'unique_together': {('idUsuario', 'anime')},
            },
        ),
    ]
